name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/receipt:latest

  deploy:
    name: Deploy on Server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH and deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/receipt:latest
            docker stop receipt || true
            docker system prune -f
            docker run -d --restart unless-stopped -p 3009:3000 --name receipt ${{ secrets.DOCKERHUB_USERNAME }}/receipt:latest
